version: '3'

services:
  php-fpm:
    build: php-fpm
    container_name: web-docker-php-fpm
    working_dir: /application
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./application:/application

  nginx:
    image: nginx:latest
    container_name: web-docker-nginx
    working_dir: /application
    ports:
      - "80:80"
    volumes:
      - ./application:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
